[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
compliance_router = "DMSJPGeWdenYtxCxqpEH2Jm9gJTSuacujo9doRDgaiSX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"
